<?php
########################################################################
#
# Theme : theme_bootstrap_mosaic
# Created : 2015-03-22 - 18:05:19
#
# Auto generated by Fluid-Template-Manager
#
# www.fluid-template-manager.de
#
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title'            => 'Theme-Bootstrap-Mosaic',
	'description'      => 'New Theme, generated by FTM
Inherit from: theme_bootstrap
',
	'category'         => 'templates',
	'shy'              => 0,
	'version'          => '0.0.1',
	'dependencies'     => '',
	'conflicts'        => '',
	'priority'         => 'bottom',
	'loadOrder'        => '',
	'module'           => '',
	'state'            => 'beta',
	'uploadfolder'     => 0,
	'createDirs'       => '',
	'modify_tables'    => '',
	'clearcacheonload' => 0,
	'lockType'         => '',
	'author'           => '',
	'author_email'     => '',
	'author_company'   => '',
	'CGLcompliance'      => '',
	'CGLcompliance_note' => '',
	'constraints' => array(
		'depends' => array(
			'php' => '5.2.0-0.0.0',
			'typo3' => '6.2.0-6.2.99',
			'themes' => '2.1.0-2.3.99',
			'theme_bootstrap' => '0.1.0-0.0.0',
			'themes_gridelements' => '0.1.0-1.0.0',
            'dyncss' => '0.7.0 - 0.7.99',
            'dyncss_less' => '0.7.0 - 0.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'_md5_values_when_last_written' => ''
);

?>
