<?php
########################################################################
#
# Theme : theme_bootstrap_mosaic
# Created : 2015-03-22 - 18:05:19
#
# Auto generated by Fluid-Template-Manager
#
# www.fluid-template-manager.de
#
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title'            => 'Mosaic Bootstrap Theme',
    'description'      => 'TYPO3 compatible adaption of the \"Mosaic - Responsive Professional Theme\" by simpleqode',
    'category'         => 'templates',
    'shy'              => 0,
    'version'          => '7.0.0',
    'dependencies'     => '',
    'conflicts'        => '',
    'priority'         => 'bottom',
    'loadOrder'        => '',
    'module'           => '',
    'state'            => 'beta',
    'uploadfolder'     => 0,
    'createDirs'       => '',
    'modify_tables'    => '',
    'clearcacheonload' => 0,
    'lockType'         => '',
    'author'           => 'Kerstin Finke, Andrea Moroni',
    'author_email'     => 'info@kerstin-finke.de,info@web-to-date.com',
    'author_company'   => '',
    'CGLcompliance'      => '',
    'CGLcompliance_note' => '',
    'constraints' => array(
        'depends' => array(
            'typo3' => '7.6.0-7.6.99',
            'theme_bootstrap' => '7.0.0-7.99.99'
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
    '_md5_values_when_last_written' => ''
);
